name: Java CI with Gradle

on:
  push:
    branches: [develop]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Import GPG key
        run: |
          echo "$GPG_SIGNING_KEY_PW" | gpg --batch --import --yes --passphrase-fd 0 <(echo -n "$GPG_SIGNING_KEY_B64" | base64 --decode)
        env:
          GPG_SIGNING_KEY_B64: ${{ secrets.GPG_PRIVATE_KEY_B64 }}
          GPG_SIGNING_KEY_PW: ${{ secrets.GPG_PASSPHRASE }}

      - name: Setup GPG key information
        run: |
          mkdir -p ~/.gradle
          echo "signing.gnupg.passphrase=${GPG_SIGNING_KEY_PW}" >> ~/.gradle/gradle.properties
        env:
          GPG_SIGNING_KEY_PW: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build package
        run: ./gradlew clean build
